name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1.83.0
        with:
          ruby-version: "2.7"
          bundler-cache: true
      #- name: Install Ruby dependencies
        #run: bundle update --bundler && bundle install
      - name: Run script
        run: |
          gem install bashcov codecov
          bashcov script.sh
      - name: "Upload reports to Codecov"
        uses: codecov/codecov-action@v2
        with:
          directory: "${{ github.workspace }}/coverage"
          files: "codecov-result.json"
